### ISSUE TITLE
About how to evaluate by FID

### ISSUE THREAD

**Issue by DianaNerualNetwork** [pfriedri/wdm-3d#3]
Dear Author,

Thanks for your impressive work! It is so amazing!
I wonder to know how to use that pretrained weight to evaluate our generation? Did that any related code released? Or any detail description for that?

**Comment by pfriedri** [comment]
@DianaNerualNetwork thank you for your interest in our work. 

This part of the code is indeed not yet in the repository, thanks for pointing that out. 
I'll add it as soon as possible.

**Comment by DianaNerualNetwork** [comment]
您好，我已收到您的来信，谢谢。

**Comment by DianaNerualNetwork** [comment]
Thanks for your kindness, we have confused about that for a week, we try to evaluate it by 3D to 2D. It is hard to find some related code to evaluate 3D FID

**Comment by pfriedri** [comment]
@DianaNerualNetwork I'm currently cleaning up our evaluation code and we'll release it soon, but if you just want to know how to compute 3D FID scores, you can have a look at https://github.com/batmanlab/HA-GAN/blob/master/evaluation/fid_score.py (our implementation is very similar)

**Comment by pfriedri** [comment]
@DianaNerualNetwork I just added the code. I hope this answers your question.
