### ISSUE TITLE
about training logs

### ISSUE THREAD

**Issue by Devil-Ideal** [pfriedri/wdm-3d#8]
Hi ! It's an awesome work. Can you share the training logs, especially the decline curve of loss ?

**Comment by pfriedri** [comment]
@Devil-Ideal thanks for your interest in our work. I attached the log of a training on BraTS 128 x 128 x 128. You can see the overall MSE between ground truth and predicted wavelet coefficients `loss/MSE` as well as the loss curves over all 8 wavelet subbands `loss/mse_wav_hhh`-`loss/mse_wav_lll`. Hope this answers your question.

![image](https://github.com/user-attachments/assets/359cf2fe-995c-4e09-8286-9cf778b3fb84)

**Comment by Devil-Ideal** [comment]
> @Devil-Ideal thanks for your interest in our work. I attached the log of a training on BraTS 128 x 128 x 128. You can see the overall MSE between ground truth and predicted wavelet coefficients `loss/MSE` as well as the loss curves over all 8 wavelet subbands `loss/mse_wav_hhh`-`loss/mse_wav_lll`. Hope this answers your question.
> 
> ![image](https://private-user-images.githubusercontent.com/101359393/381433706-359cf2fe-995c-4e09-8286-9cf778b3fb84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMzQ4MzcsIm5iZiI6MTczMDMzNDUzNywicGF0aCI6Ii8xMDEzNTkzOTMvMzgxNDMzNzA2LTM1OWNmMmZlLTk5NWMtNGUwOS04Mjg2LTljZjc3OGIzZmI4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwMDI4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjA5YTg2ZGE2ODY0MjNkMDZmNWIyNGZjZTFjNmE0NWQ1YmUwNjQ5YTk0MzdhN2JhYjlkZWM3MjU1YTk0ODRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rq0s6VsBN_7PiIsB11iaN-V1OQwKFIiSRaOMnofCsbM)

Thanks a lot ! I didn't use the  wavelet transform and train the model in the voxel space directly with a CT dataset. Maybe it's because I cropped the image into patches but didn't give any conditions, which resulted in the unconditional generation still not being very good.
