### ISSUE TITLE
Results SSIM

### ISSUE THREAD

**Issue by lukas-folle-snkeos** [pfriedri/wdm-3d#9]
Hi there, thank you for open-sourcing the code to reproduce your results. While reading the paper I noticed the following:

![image](https://github.com/user-attachments/assets/cdc5dff1-21d6-4ded-8596-c1a2d6a7cb6c)

Wouldn't a high MS-SSIM be better (arrow up) and the proposed method is slightly behind the comparison in terms of SSIM, while being better in FID?

**Comment by pfriedri** [comment]
@lukas-folle-snkeos Thank you for your interest in our work. In fact, the MS-SSIM score is mostly used to compare a generated image with a ground truth image, e.g. in a paired image-to-image translation task (also see section 4 of [this paper](https://arxiv.org/abs/2410.17664)) . We use the MS-SSIM score to compare the generated images with each other (not generated with ground truth, but generated with generated, as no ground truth is available). In this case, a low MS-SSIM score indicates that the generated images are diverse. On the other hand, a high MS-SSIM score would in this case indicate that the generated images are very similar, which would be a sign of mode collapse.

I hope this answers your question.

**Comment by lukas-folle-snkeos** [comment]
That explains it! Just found it confusing that in the results section you mention outperforming SOTA and have the table right next to it. Next time I'll take a closer look 😄
